/**
 * The two environment files, and the division of labour between them.
 *
 * `.env` is yours: it holds the secrets and you own its contents. `.env.local` is generated on
 * every run and holds only what this directory's identity implies — which database, which
 * ports. Keeping them apart is what lets the derived half be rewritten freely without ever
 * putting a secret at risk of being clobbered.
 *
 * Both are gitignored already: `.gitignore` covers `.env.*` and `*.local`.
 */
import { randomBytes } from 'node:crypto'
import { existsSync, readFileSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'

const HEADER = `# GENERATED by \`pnpm start\` — do not edit; every run overwrites this file.
#
# Derived from this directory, so several worktrees can run at once without colliding.
# Secrets live in .env and are never written here.
#
# Loaded BEFORE .env. \`process.loadEnvFile\` does not overwrite an already-set variable, so
# loading first is what makes these values win — while the real process environment still beats
# both, which is what keeps CI pointed at its own database.
`

/**
 * `ADMIN_ORIGIN` is what makes the administrative site work in a **browser** rather than only
 * under `curl`.
 *
 * `app.ts` allows CORS on administrative routes from `config.adminOrigin ?? false` — so with the
 * variable unset the answer is `false`, and every request the admin client makes is refused by
 * the browser before it reaches a handler. Nothing about that is visible server-side, which is
 * why it survived: the routes are correct, the site loads, and only the fetches fail.
 *
 * It is deliberately absent in **deployed** environments, where Caddy serves `admin.<host>` and
 * proxies `/api/*` beneath it, so administrative requests are same-origin and there is nothing
 * for CORS to allow. Local is the only topology that needs it.
 */
export const renderEnvLocal = ({ databaseUrl, apiPort, webOrigin, apiOrigin, adminOrigin }) =>
  `${HEADER}
DATABASE_URL=${databaseUrl}
API_PORT=${apiPort}
WEB_ORIGIN=${webOrigin}
ADMIN_ORIGIN=${adminOrigin}
VITE_API_BASE_URL=${apiOrigin}
`

export const writeEnvLocal = (root, values) => {
  writeFileSync(join(root, '.env.local'), renderEnvLocal(values), 'utf8')
}

/**
 * Creates `.env` from the example when it is absent, generating real secrets rather than
 * copying the placeholders through — a placeholder pepper would work, which is worse than
 * failing, because it would make every local hash trivially reproducible.
 *
 * An existing `.env` is never read, rewritten, or inspected.
 */
export const ensureEnvFile = (root) => {
  const envPath = join(root, '.env')
  if (existsSync(envPath)) return 'present'

  const example = readFileSync(join(root, '.env.example'), 'utf8')
  const generated = example
    .replace(
      /^AUTH_PASSWORD_PEPPER=.*$/m,
      `AUTH_PASSWORD_PEPPER=${randomBytes(48).toString('base64')}`,
    )
    .replace(
      /^AUTH_ATTEMPT_HASH_KEY=.*$/m,
      `AUTH_ATTEMPT_HASH_KEY=${randomBytes(48).toString('base64')}`,
    )

  writeFileSync(envPath, generated, 'utf8')
  return 'created'
}
